on:
  push:
    branches:
      - "main"
name: Build_Waqqly_Web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Obtain the latest version of actions"
        uses: actions/checkout@main

      - name: "Authenticate with Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push the Waqq.ly image to ACR"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd ./waqqly-web
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/waqqly-app:latest . 
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/waqqly-app:latest
