on:
  push:
    branches:
      - 'main'
name: Build_Waqqly_Web

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            cd ./waggly-web
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/waqqly-app:latest . 
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/waqqly-app:latest
